### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jeffh-cloudflare** [albertogeniola/terraform-gce-vyos#1]
Hello!

I found your repo via Google search just now. I am very interested in using this packer/Terraform script but have little/no experience with Packer.

Are you able to provide any additional insight in terms of how to use the script beyond what's currently in your README.md?

Do I need to create Google Cloud storage bucket(s)? Upload a VyOS ISO image to a Google Cloud storage bucket?

Any additional insights you could provide would be greatly appreciated!

Thanks Alberto!

**Comment by albertogeniola** [comment]
Hi!

Thanks a lot for the feedback. I've just performed a major refactor on the module and completely removed the need of packer: the GCE vyos image is now built via GitHub actions.

Moreover, you can find a very basic example on how to use this module in the examples directory. Have fun!

**Comment by jeffh-cloudflare** [comment]
@albertogeniola thanks so much for the work you did! I ended up using one of your pre-built images. I'm running into another issue with the GCE Agent. I'm going to open another issue but I just wanted to thank you for the work you did. It's very helpful!!!
