### ISSUE TITLE
exceptions.MetadataException: Cannot access metadata

### ISSUE THREAD

**Issue by ppwicho** [albertogeniola/terraform-gce-vyos#5]
Hi albertogeniola, 

I just compile VyOS for GCE but after load a fresh installation I'm watching this error at the console: 

```log
Dec  5 21:34:21 vyos-gce systemd[1]: conf_reloader.service: Service RestartSec=30s expired, scheduling restart.
Dec  5 21:34:21 vyos-gce systemd[1]: conf_reloader.service: Scheduled restart job, restart counter is at 1791.
Dec  5 21:34:21 vyos-gce systemd[1]: Stopped VyOs configuration reloader.
Dec  5 21:34:21 vyos-gce systemd[1]: Started VyOs configuration reloader.
Dec  5 21:34:21 vyos-gce python[11596]: Traceback (most recent call last):
Dec  5 21:34:22 vyos-gce python[11596]:   File "/opt/gce_helper/conf_reloader.py", line 7, in <module>
Dec  5 21:34:22 vyos-gce python[11596]:     from configuration import configuration
Dec  5 21:34:22 vyos-gce python[11596]:   File "/opt/gce_helper/configuration.py", line 55, in <module>
Dec  5 21:34:22 vyos-gce python[11596]:     configuration = Configuration.load_from_metadata()
Dec  5 21:34:22 vyos-gce python[11596]:   File "/opt/gce_helper/configuration.py", line 42, in load_from_metadata
Dec  5 21:34:22 vyos-gce python[11596]:     pubsub_subscription = str(get_metadata(metadata_path="/computeMetadata/v1/instance/attributes/pubsub-subscription", alt="text"))
Dec  5 21:34:22 vyos-gce python[11596]:   File "/opt/gce_helper/utils.py", line 36, in get_metadata
Dec  5 21:34:22 vyos-gce python[11596]:     raise MetadataException(f"Cannot access metadata: {metadata_path}. Return code: {resp.status_code}")
Dec  5 21:34:22 vyos-gce python[11596]: exceptions.MetadataException: Cannot access metadata: /computeMetadata/v1/instance/attributes/pubsub-subscription. Return code: 404
Dec  5 21:34:22 vyos-gce systemd[1]: conf_reloader.service: Main process exited, code=exited, status=1/FAILURE
Dec  5 21:34:22 vyos-gce systemd[1]: conf_reloader.service: Failed with result 'exit-code'.
```

**Comment by ppwicho** [comment]
I just see this at the documentation: 

This module uses a GCS file to hold the configuration state, fetched via pubsub event by a python daemon running on the VyOS instance. However, the module still allows the developer to pass the user-data content, in case that is preferred.

But I can't find where o how to do it.  Sorry, maybe this is a Terraform basics, but I'm not aware to much about terraform in my daily basics.

**Comment by ppwicho** [comment]
I think I just found the solution here: 

https://qiita.com/khayama/items/0773f9f9efd2ba1ecddb 


Since we are not using Terraform, we will stop and disable automatic startup of the following services.


sudo sh -c 'echo 127.0.1.1 $(hostname) >> /etc/hosts'
sudo systemctl stop conf_reloader.service
sudo systemctl disable conf_reloader.service
sudo systemctl stop google-osconfig-agent
sudo systemctl disable google-osconfig-agent


From here, run the command configure set --> commit You can perform a series of VyOS settings such as save!

**Comment by albertogeniola** [comment]
Hi @ppwicho ,
exactly, you can disable the daemon and that will work. The module assumes you will use terraform for handling the configuration. If you plan to work manually, you can simply create an instance from the image, disable the daemon and work as you would with a normal VyOS instance. That's not the case this repo addresses, but it's totally doable.
